kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.liferay.persistence.pvcName | quote }}
  labels:
    app.kubernetes.io/name: {{ include "liferay.name" . }}
    helm.sh/chart: {{ include "liferay.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: "standard"